apiVersion: v1
kind: Service
metadata:
  name: flask-blog-service
spec:
  type: NodePort
  selector:
    app: flask-blog
  ports:
    - protocol: TCP
      port: 5000         # internal cluster port
      targetPort: 5000   # container port
      nodePort: 30007    # port you access from browser
